# Generic kernels. `generate_carrier!` produces the carrier with a textbook NCO
# (numerically-controlled oscillator): a UInt32 phase accumulator advanced by a fixed
# frequency word each sample. One full UInt32 = one carrier cycle = N table entries, so
# the table index is `acc >> (32 - log2(N))`. Resolution is uniform and dead-zone-free
# (`sampling_frequency / 2^32` per step) and the accumulator never drifts (it is an
# exact closed form `acc[n] = freq_word*n + acc_offset` mod 2^32).
# `lookup_sincos!` looks up sin/cos for a supplied array of phase indices.
#
# Type parameters used throughout: `T` = output element type, `N` = table steps per
# cycle, `W` = SIMD lane count for the backend.

"""
    cycles_per_sample(frequency, sampling_frequency)

Normalised frequency `frequency / sampling_frequency` (cycles per sample) — pass the
result as the frequency argument of [`generate_carrier!`](@ref),
[`generate_carrier`](@ref) or [`generate_carrier4`](@ref), e.g.
`generate_carrier!(sin_out, cos_out, table, cycles_per_sample(1000, 2e6))`.
"""
cycles_per_sample(frequency, sampling_frequency) = frequency / sampling_frequency

# Convert a `phase` keyword to an integer phase offset in table steps:
#   Integer → table steps (exact);  Real → cycles (fraction of a full cycle).
@inline _phase_steps(phase::Integer, steps) = Int(phase)
@inline _phase_steps(phase::Real, steps) = round(Int, phase * steps)

# 2^32 — one full turn of the UInt32 phase accumulator equals one carrier cycle.
const _TWO32 = 4.294967296e9

# cycles-per-sample → UInt32 frequency word. The round/truncate wraps correctly for
# negative cps (receding Doppler) via two's complement — no clamp, no sign error.
@inline _freq_word(cps::Real) = unsafe_trunc(UInt32, round(Int64, cps * _TWO32))

# ===== generate_carrier! =====
"""
    generate_carrier!(sin_out, cos_out, table, freq_word::Integer;       phase=0, backend=…)
    generate_carrier!(sin_out, cos_out, table, cycles_per_sample::Real;  phase=0, backend=…)
    generate_carrier!(sin_out, cos_out, table; frequency, sampling_frequency, phase=0, backend=…)

Fill `sin_out`/`cos_out` (element type `T`) with a carrier generated by a textbook NCO
(numerically-controlled oscillator): a `UInt32` phase accumulator is advanced by a
fixed frequency word each sample, and the top `log2(steps)` bits index the table. One
full `UInt32` is one carrier cycle, so the frequency resolution is uniform and
dead-zone-free — `sampling_frequency / 2^32` cycles per sample — and the phase never
drifts (it is the exact closed form `acc[n] = freq_word·n + offset` mod 2^32, computed
per lane with no division).

The low-level form takes a raw `freq_word` (a `UInt32`, `0 ≤ freq_word ≤ 2^32-1`); a
`cycles_per_sample::Real` is converted as `freq_word = round(cps·2^32)` (wraps via
two's complement for negative/receding Doppler); the keyword form takes a `frequency`
and `sampling_frequency` directly (`cycles_per_sample = frequency / sampling_frequency`).
`phase` is the initial carrier phase, default 0: an `Integer` is **table steps**
(exact), a `Real` is **cycles**.
"""
function generate_carrier!(sin_out::AbstractVector{T}, cos_out::AbstractVector{T},
                           table::SinCosTable{T,N}, freq_word::Integer;
                           phase::Real = 0, backend::Backend = default_backend(T, N)) where {T,N}
    length(sin_out) == length(cos_out) || throw(DimensionMismatch("sin/cos lengths differ"))
    (0 ≤ freq_word ≤ typemax(UInt32)) ||
        throw(ArgumentError("need 0 ≤ freq_word ≤ typemax(UInt32) = $(typemax(UInt32))"))
    _generate!(sin_out, cos_out, table, UInt32(freq_word), _phase_steps(phase, N), backend)
end
function generate_carrier!(sin_out::AbstractVector{T}, cos_out::AbstractVector{T},
                           table::SinCosTable{T,N}, cycles_per_sample::Real; kw...) where {T,N}
    generate_carrier!(sin_out, cos_out, table, _freq_word(cycles_per_sample); kw...)
end

# Direct frequency / sampling-frequency form (keyword args avoid any ambiguity with the
# low-level integer `freq_word` method):
#   generate_carrier!(sin_out, cos_out, table; frequency = 1000, sampling_frequency = 2e6)
function generate_carrier!(sin_out::AbstractVector{T}, cos_out::AbstractVector{T},
                           table::SinCosTable{T,N};
                           frequency::Real, sampling_frequency::Real, kw...) where {T,N}
    generate_carrier!(sin_out, cos_out, table, cycles_per_sample(frequency, sampling_frequency); kw...)
end

# NCO bit-layout helpers. One full UInt32 accumulator = one carrier cycle = N table
# entries; the index for an accumulator value is its top `log2(N)` bits.
@inline _index_shift(::Val{N}) where {N} = 32 - trailing_zeros(N)   # compile-time constant
# Initial-phase offset in accumulator units: po_steps table-steps → top bits.
@inline _acc_offset(po_steps, ::Val{N}) where {N} = UInt32(mod(po_steps, N) << _index_shift(Val(N)))

# Constant lane vectors Vec{W,UInt32}([0,1,…,W-1]) for each backend width (64 = AVX-512,
# 32 = AVX2, 16 = NEON, 1 = Portable). Generic over W via a generated constant so the
# ntuple folds to a compile-time literal vector.
@inline @generated _lanes_u32(::Val{W}) where {W} =
    :(Vec{$W,UInt32}($(Expr(:tuple, (UInt32(j - 1) for j in 1:W)...))))

# Initialise one NCO accumulator of W lanes whose lane 0 is absolute sample `start`:
#   acc[j] = freq_word*(start+j) + acc_offset   (all UInt32, natural mod-2^32 wrap)
# Built SIMD with no division — purely a multiply-add over the constant lane vector.
@inline function _init_acc(::Val{W}, freq_word::UInt32, acc_offset::UInt32, start::Integer) where {W}
    Vec{W,UInt32}(freq_word) * (_lanes_u32(Val(W)) + UInt32(start)) + Vec{W,UInt32}(acc_offset)
end

# 4 independent NCO accumulators run interleaved so their stores/lookups overlap.
# Hand-unrolled with plain locals — a tuple/closure formulation boxes the reassigned
# state and is ~100× slower.
function _generate!(sin_out, cos_out, table::SinCosTable{T,N},
                    freq_word::UInt32, phase_offset, backend::Union{AVX512,AVX2,Neon}) where {T,N}
    _generate_simd!(sin_out, cos_out, table, freq_word, phase_offset, backend, _vwidth(backend, T))
end
function _generate_simd!(sin_out, cos_out, table::SinCosTable{T,N},
                         freq_word::UInt32, phase_offset, backend, ::Val{W}) where {T,N,W}
    shift = _index_shift(Val(N))
    acc_offset = _acc_offset(phase_offset, Val(N))
    stride = 4W
    step_advance = freq_word * UInt32(stride)              # accumulator advance per stride
    acc1 = _init_acc(Val(W), freq_word, acc_offset, 0)
    acc2 = _init_acc(Val(W), freq_word, acc_offset, W)
    acc3 = _init_acc(Val(W), freq_word, acc_offset, 2W)
    acc4 = _init_acc(Val(W), freq_word, acc_offset, 3W)
    prepared_table = _prepare(backend, table)              # materialise table in registers once
    num_samples = length(sin_out); chunk_start = 0
    @inbounds while chunk_start + stride <= num_samples
        # store each result immediately (keep ≤2 result vectors live → no spills);
        # the four lookups are still independent so out-of-order execution overlaps them.
        sin1, cos1 = _apply(backend, prepared_table, convert(Vec{W,T}, acc1 >> shift))
        sin_out[VecRange{W}(chunk_start + 1)]      = sin1; cos_out[VecRange{W}(chunk_start + 1)]      = cos1
        sin2, cos2 = _apply(backend, prepared_table, convert(Vec{W,T}, acc2 >> shift))
        sin_out[VecRange{W}(chunk_start + W + 1)]  = sin2; cos_out[VecRange{W}(chunk_start + W + 1)]  = cos2
        sin3, cos3 = _apply(backend, prepared_table, convert(Vec{W,T}, acc3 >> shift))
        sin_out[VecRange{W}(chunk_start + 2W + 1)] = sin3; cos_out[VecRange{W}(chunk_start + 2W + 1)] = cos3
        sin4, cos4 = _apply(backend, prepared_table, convert(Vec{W,T}, acc4 >> shift))
        sin_out[VecRange{W}(chunk_start + 3W + 1)] = sin4; cos_out[VecRange{W}(chunk_start + 3W + 1)] = cos4
        acc1 += step_advance; acc2 += step_advance; acc3 += step_advance; acc4 += step_advance
        chunk_start += stride
    end
    _generate_tail!(sin_out, cos_out, table, freq_word, acc_offset, chunk_start + 1)
end

function _generate!(sin_out, cos_out, table::SinCosTable{T,N},
                    freq_word::UInt32, phase_offset, ::Portable) where {T,N}
    _generate_tail!(sin_out, cos_out, table, freq_word, _acc_offset(phase_offset, Val(N)), 1)
end
@inline function _generate_tail!(sin_out, cos_out, table::SinCosTable{T,N},
                                 freq_word::UInt32, acc_offset::UInt32, sample) where {T,N}
    shift = _index_shift(Val(N))
    @inbounds while sample <= length(sin_out)
        index = Int((freq_word * UInt32(sample - 1) + acc_offset) >> shift)
        sin_out[sample] = table.sin[index + 1]; cos_out[sample] = table.cos[index + 1]
        sample += 1
    end
    sin_out, cos_out
end

# ===== lookup_sincos! (lookup from a phase-index array) =====
"""
    lookup_sincos!(sin_out, cos_out, phase_indices, table; backend=default_backend(table))

Look up sin/cos for each integer phase index in `phase_indices` (taken mod `steps`).
"""
function lookup_sincos!(sin_out::AbstractVector{T}, cos_out::AbstractVector{T},
                        phase_indices::AbstractVector{T}, table::SinCosTable{T,N};
                        backend::Backend = default_backend(T, N)) where {T,N}
    length(sin_out) == length(cos_out) == length(phase_indices) || throw(DimensionMismatch())
    _lookup!(sin_out, cos_out, phase_indices, table, backend)
end

function _lookup!(sin_out, cos_out, phase_indices, table::SinCosTable{T,N},
                  backend::Union{AVX512,AVX2,Neon}) where {T,N}
    _lookup_simd!(sin_out, cos_out, phase_indices, table, backend, _vwidth(backend, T))
end
function _lookup_simd!(sin_out, cos_out, phase_indices, table::SinCosTable{T,N},
                       backend, ::Val{W}) where {T,N,W}
    index_mask = T(N - 1); num_samples = length(phase_indices); sample = 1
    prepared_table = _prepare(backend, table)
    @inbounds while sample + W - 1 <= num_samples
        lane = VecRange{W}(sample)
        sin_vec, cos_vec = _apply(backend, prepared_table, phase_indices[lane] & index_mask)
        sin_out[lane] = sin_vec; cos_out[lane] = cos_vec
        sample += W
    end
    _lookup_tail!(sin_out, cos_out, phase_indices, table, sample)
end
function _lookup!(sin_out, cos_out, phase_indices, table::SinCosTable{T,N}, ::Portable) where {T,N}
    _lookup_tail!(sin_out, cos_out, phase_indices, table, 1)
end
@inline function _lookup_tail!(sin_out, cos_out, phase_indices, table::SinCosTable{T,N}, sample) where {T,N}
    @inbounds while sample <= length(phase_indices)
        index = Int(phase_indices[sample]) & (N - 1)
        sin_out[sample] = table.sin[index + 1]; cos_out[sample] = table.cos[index + 1]
        sample += 1
    end
    sin_out, cos_out
end

# ===== Portable iterator support =====
# The iterators (generate_carrier/generate_carrier4) are SIMD-first, but must still
# work on any CPU/type combo that resolves to the Portable backend (e.g. Int16/Int32
# on AVX2 or NEON). Use width 1 (Vec{1,T}) with a scalar table lookup — correct, just
# not vectorised. (The array kernels generate_carrier!/lookup_sincos! already have
# dedicated scalar Portable paths.)
_vwidth(::Portable, ::Type{T}) where {T} = Val(1)
@inline _prepare(::Portable, table::SinCosTable) = (table.sin, table.cos)
@inline function _apply(::Portable, tables, index::Vec{1,T}) where {T}
    k = Int(index[1]) + 1
    @inbounds (Vec{1,T}(tables[1][k]), Vec{1,T}(tables[2][k]))
end
